apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: serverless-platform
spec:
  workload:
    definition:
      apiVersion: v1
      kind: ConfigMap
  schematic:
    cue:
      template: |
        parameter: {
          resources: {
            requests: {
              cpu: *"100m" | string
              memory: *"128Mi" | string
            }
          }
          replicas: *1 | int
          env?: [...string] // or array of objects you can convert to text
        }
        
        output: {
          apiVersion: "v1"
          kind: "ConfigMap"
          metadata: {
            name: context.name
          }
          data: {
            cpu-request:      parameter.resources.requests.cpu
            memory-request:   parameter.resources.requests.memory
            replicas:         "\(parameter.replicas)"

            if parameter.env != _|_ {
              env:            "\(parameter.env)"
            }
          }
        }


