name: CI
on:
  push:
    branches:
      - dev
      - main
      - r[1-9]
  pull_request:
    branches:
      - dev
      - main
      - r[1-9]
jobs:
  build-and-push-sal-scripts:
    name: Build and push sal-scripts
    uses: eu-nebulous/github-actions/.github/workflows/build-and-push-container-image.yml@main
    with:
      context: .
      image-name: sal-scripts
    secrets: inherit
